# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 674)
        MainWindow.setStyleSheet("background-color: black")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 1061, 581))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 0, 255, 255), stop:1 rgba(255, 15, 107, 255));\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 131, 31))
        self.label_2.setStyleSheet("background-color: no color;\n"
"font: 16pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 131, 31))
        self.label_3.setStyleSheet("background-color: no color;\n"
"font: 16pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 131, 31))
        self.label_4.setStyleSheet("background-color: no color;\n"
"font: 16pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 131, 31))
        self.label_5.setStyleSheet("background-color: no color;\n"
"font: 16pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 270, 131, 31))
        self.label_6.setStyleSheet("background-color: no color;\n"
"font: 16pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 330, 131, 31))
        self.label_7.setStyleSheet("background-color: no color;\n"
"font: 16pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20, 390, 131, 31))
        self.label_8.setStyleSheet("background-color: no color;\n"
"font: 16pt \"Segoe UI\";")
        self.label_8.setObjectName("label_8")
        self.id_field = QtWidgets.QLineEdit(self.frame)
        self.id_field.setGeometry(QtCore.QRect(170, 30, 221, 31))
        self.id_field.setStyleSheet("background-color: white;\n"
"font: 14pt \"Segoe UI\";")
        self.id_field.setText("")
        self.id_field.setObjectName("id_field")
        self.name_field = QtWidgets.QLineEdit(self.frame)
        self.name_field.setGeometry(QtCore.QRect(170, 90, 221, 31))
        self.name_field.setStyleSheet("background-color: white;\n"
"font: 14pt \"Segoe UI\";")
        self.name_field.setText("")
        self.name_field.setObjectName("name_field")
        self.email_field = QtWidgets.QLineEdit(self.frame)
        self.email_field.setGeometry(QtCore.QRect(170, 150, 221, 31))
        self.email_field.setStyleSheet("background-color: white;\n"
"font: 14pt \"Segoe UI\";")
        self.email_field.setText("")
        self.email_field.setObjectName("email_field")
        self.phoneno_field = QtWidgets.QLineEdit(self.frame)
        self.phoneno_field.setGeometry(QtCore.QRect(170, 210, 221, 31))
        self.phoneno_field.setStyleSheet("background-color: white;\n"
"font: 14pt \"Segoe UI\";")
        self.phoneno_field.setText("")
        self.phoneno_field.setObjectName("phoneno_field")
        self.address_field = QtWidgets.QTextEdit(self.frame)
        self.address_field.setGeometry(QtCore.QRect(170, 390, 221, 81))
        self.address_field.setStyleSheet("background-color: white;")
        self.address_field.setObjectName("address_field")
        self.gender_field = QtWidgets.QComboBox(self.frame)
        self.gender_field.setGeometry(QtCore.QRect(170, 330, 221, 31))
        self.gender_field.setStyleSheet("background-color: white;")
        self.gender_field.setObjectName("gender_field")
        self.gender_field.addItem("")
        self.gender_field.addItem("")
        self.date_field = QtWidgets.QDateEdit(self.frame)
        self.date_field.setGeometry(QtCore.QRect(170, 270, 221, 31))
        self.date_field.setStyleSheet("background-color: white")
        self.date_field.setObjectName("date_field")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(430, 20, 131, 41))
        self.label_9.setStyleSheet("background-color: no color;")
        self.label_9.setObjectName("label_9")
        self.search_field = QtWidgets.QLineEdit(self.frame)
        self.search_field.setGeometry(QtCore.QRect(560, 20, 231, 31))
        self.search_field.setStyleSheet("background-color: white;")
        self.search_field.setObjectName("search_field")
        self.add_button = QtWidgets.QPushButton(self.frame)
        self.add_button.setGeometry(QtCore.QRect(20, 520, 101, 41))
        self.add_button.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(42, 255, 241);")
        self.add_button.setObjectName("add_button")
        self.modify_button = QtWidgets.QPushButton(self.frame)
        self.modify_button.setGeometry(QtCore.QRect(160, 520, 101, 41))
        self.modify_button.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(42, 255, 241);\n"
"")
        self.modify_button.setObjectName("modify_button")
        self.delete_button = QtWidgets.QPushButton(self.frame)
        self.delete_button.setGeometry(QtCore.QRect(290, 520, 101, 41))
        self.delete_button.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(42, 255, 241);\n"
"")
        self.delete_button.setObjectName("delete_button")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(430, 100, 621, 461))
        self.tableWidget.setStyleSheet("background-color: white;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.search_button = QtWidgets.QPushButton(self.frame)
        self.search_button.setGeometry(QtCore.QRect(820, 20, 101, 31))
        self.search_button.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(42, 255, 241);\n"
"")
        self.search_button.setObjectName("search_button")
        self.error_mod = QtWidgets.QLabel(self.frame)
        self.error_mod.setGeometry(QtCore.QRect(170, 480, 211, 31))
        self.error_mod.setStyleSheet("background-color: no color;")
        self.error_mod.setObjectName("error_mod")
        self.error_search = QtWidgets.QLabel(self.frame)
        self.error_search.setGeometry(QtCore.QRect(760, 60, 171, 31))
        self.error_search.setStyleSheet("background-color: no color;")
        self.error_search.setObjectName("error_search")
        self.showall_button = QtWidgets.QPushButton(self.frame)
        self.showall_button.setGeometry(QtCore.QRect(950, 20, 101, 31))
        self.showall_button.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(42, 255, 241);\n"
"")
        self.showall_button.setObjectName("showall_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1061, 51))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(85, 0, 255, 255), stop:1 rgba(255, 15, 107, 255));\n"
"border-radius: 20px;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">ID:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Name:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">E-mail ID:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Phone No:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">D.O.B.:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Gender:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ffffff;\">Address:</span></p></body></html>"))
        self.gender_field.setItemText(0, _translate("MainWindow", "Male"))
        self.gender_field.setItemText(1, _translate("MainWindow", "Female"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Search:</span></p></body></html>"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.modify_button.setText(_translate("MainWindow", "Modify"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "E-mail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Phone No"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "D.O.B."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Address"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.error_mod.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.error_search.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\"><br/></span></p></body></html>"))
        self.showall_button.setText(_translate("MainWindow", "Show All"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#ffffff;\">Student Management System</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
